
package myws_soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.slavkoprogrammingworld.ObjectFactory;
import com.slavkoprogrammingworld.User;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ManageUsers", targetNamespace = "http://SlavkoProgrammingWorld.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ManageUsers {


    /**
     * 
     * @return
     *     returns java.util.List<com.slavkoprogrammingworld.User>
     */
    @WebMethod(action = "get_users")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://SlavkoProgrammingWorld.com", className = "com.slavkoprogrammingworld.GetUsers")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://SlavkoProgrammingWorld.com", className = "com.slavkoprogrammingworld.GetUsersResponse")
    @Action(input = "get_users", output = "http://SlavkoProgrammingWorld.com/ManageUsers/getUsersResponse")
    public List<User> getUsers();

    /**
     * 
     * @param userid
     * @return
     *     returns java.lang.String
     * @throws NoUserWithSuchIDException
     */
    @WebMethod(action = "get_user_name_by_id")
    @WebResult(name = "USERNAME", targetNamespace = "")
    @RequestWrapper(localName = "getUserNameById", targetNamespace = "http://SlavkoProgrammingWorld.com", className = "com.slavkoprogrammingworld.GetUserNameById")
    @ResponseWrapper(localName = "getUserNameByIdResponse", targetNamespace = "http://SlavkoProgrammingWorld.com", className = "com.slavkoprogrammingworld.GetUserNameByIdResponse")
    @Action(input = "get_user_name_by_id", output = "http://SlavkoProgrammingWorld.com/ManageUsers/getUserNameByIdResponse", fault = {
        @FaultAction(className = NoUserWithSuchIDException.class, value = "http://SlavkoProgrammingWorld.com/ManageUsers/getUserNameById/Fault/NoUserWithSuchIDException")
    })
    public String getUserNameById(
        @WebParam(name = "USERID", targetNamespace = "")
        int userid)
        throws NoUserWithSuchIDException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(action = "set_user")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setNewUser", targetNamespace = "http://SlavkoProgrammingWorld.com", className = "com.slavkoprogrammingworld.SetNewUser")
    @ResponseWrapper(localName = "setNewUserResponse", targetNamespace = "http://SlavkoProgrammingWorld.com", className = "com.slavkoprogrammingworld.SetNewUserResponse")
    @Action(input = "set_user", output = "http://SlavkoProgrammingWorld.com/ManageUsers/setNewUserResponse")
    public boolean setNewUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(action = "set_user_obj")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setNewUserObj", targetNamespace = "http://SlavkoProgrammingWorld.com", className = "com.slavkoprogrammingworld.SetNewUserObj")
    @ResponseWrapper(localName = "setNewUserObjResponse", targetNamespace = "http://SlavkoProgrammingWorld.com", className = "com.slavkoprogrammingworld.SetNewUserObjResponse")
    @Action(input = "set_user_obj", output = "http://SlavkoProgrammingWorld.com/ManageUsers/setNewUserObjResponse")
    public boolean setNewUserObj(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(action = "set_users")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setNewUsers", targetNamespace = "http://SlavkoProgrammingWorld.com", className = "com.slavkoprogrammingworld.SetNewUsers")
    @ResponseWrapper(localName = "setNewUsersResponse", targetNamespace = "http://SlavkoProgrammingWorld.com", className = "com.slavkoprogrammingworld.SetNewUsersResponse")
    @Action(input = "set_users", output = "http://SlavkoProgrammingWorld.com/ManageUsers/setNewUsersResponse")
    public boolean setNewUsers(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0);

}
