
package myws_soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ManageUserService", targetNamespace = "http://myWS_SOAP/", wsdlLocation = "http://localhost:1234/MyWSTest?wsdl")
public class ManageUserService
    extends Service
{

    private final static URL MANAGEUSERSERVICE_WSDL_LOCATION;
    private final static WebServiceException MANAGEUSERSERVICE_EXCEPTION;
    private final static QName MANAGEUSERSERVICE_QNAME = new QName("http://myWS_SOAP/", "ManageUserService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1234/MyWSTest?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MANAGEUSERSERVICE_WSDL_LOCATION = url;
        MANAGEUSERSERVICE_EXCEPTION = e;
    }

    public ManageUserService() {
        super(__getWsdlLocation(), MANAGEUSERSERVICE_QNAME);
    }

    public ManageUserService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MANAGEUSERSERVICE_QNAME, features);
    }

    public ManageUserService(URL wsdlLocation) {
        super(wsdlLocation, MANAGEUSERSERVICE_QNAME);
    }

    public ManageUserService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MANAGEUSERSERVICE_QNAME, features);
    }

    public ManageUserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManageUserService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ManageUsers
     */
    @WebEndpoint(name = "ManageUsersPort")
    public ManageUsers getManageUsersPort() {
        return super.getPort(new QName("http://myWS_SOAP/", "ManageUsersPort"), ManageUsers.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManageUsers
     */
    @WebEndpoint(name = "ManageUsersPort")
    public ManageUsers getManageUsersPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://myWS_SOAP/", "ManageUsersPort"), ManageUsers.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MANAGEUSERSERVICE_EXCEPTION!= null) {
            throw MANAGEUSERSERVICE_EXCEPTION;
        }
        return MANAGEUSERSERVICE_WSDL_LOCATION;
    }

}
